# Name for the Conda environment
name: text2midi

channels:
    - pytorch
    - nvidia
    - xformers
    - conda-forge # Community channel, often has the latest versions
    - defaults # Default Anaconda channel

dependencies:
    # --- Core ---
    - python=3.11
    - pip
    - setuptools
    - wheel

    # --- Libraries with C components / Common Dependencies ---
    - ffmpeg
    - fluidsynth
    - pysoundfile

    # --- Torch ---
    - pytorch
    - pytorch-cuda=12.1
    - cudatoolkit

    - pip:
          # --- ML Frameworks & Tools ---
          - unsloth
          - datasets
          - huggingface-hub
          - transformers
          - wandb

          # --- Audio / MIDI Processing ---
          - librosa
          - midi2audio
          - midiutil
          - mido
          - music21
          - pretty_midi
          - pyaudio
          - pydub
          - pyfluidsynth
          - soundfile

          # --- Utilities & Others ---
          - joblib
          - llvmlite
          - numba
          - pooch
          - python-dotenv
          - tqdm
