# Conda environment configuration for TextToMIDI project
# Create environment with: conda env create -f environment.yml
# Activate environment with: conda activate text-to-midi
# (Current as of April 26, 2025)

name: text-to-midi

channels:
    - pytorch # Channel for official PyTorch builds
    - conda-forge # Recommended community channel for many packages
    - defaults # Default conda channel

dependencies:
    # --- Python Version ---
    # Using 3.11 as it's known stable with most libraries.
    # If wandb/dependencies are confirmed working with 3.12+, you can change this.
    - python=3.11

    # --- Core ML / PyTorch ---
    # CPU-only version (adjust if you have CUDA):
    - pytorch::pytorch
    - pytorch::torchvision
    - pytorch::torchaudio
    - pytorch::cpuonly # Remove this line if using CUDA below
    # GPU version (Uncomment ONE of the following lines if you have an NVIDIA GPU with CUDA):
    # - pytorch::pytorch-cuda=11.8 # Example for CUDA 11.8
    # - pytorch::pytorch-cuda=12.1 # Example for CUDA 12.1

    # --- Essential Libraries (Available via Conda) ---
    - numpy
    - requests # Often implicitly needed
    - tqdm # For progress bars
    - midiutil # For writing MIDI files
    - mido # Often a dependency for MIDI libs, good to include
    - pretty_midi # Recommended MIDI parser
    - libsndfile # Dependency for soundfile/pysoundfile
    - pip # To install packages not on conda channels

    # --- Libraries installed via Pip (within Conda env) ---
    - pip:
          - transformers # Hugging Face core library
          - huggingface_hub # For model/dataset downloads
          - tokenizers # HF tokenizers library
          - datasets # For loading HF datasets (like MidiCaps meta)
          - wandb # Weights & Biases logging
          - pydub # For audio conversion (WAV -> MP3)
          - pyfluidsynth # Python wrapper for FluidSynth (MIDI -> WAV)
          - pysoundfile # For reading/writing audio files (used by wandb.Audio)
          # Add any other pip-specific dependencies here
